### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by mjadczak** [sangria-graphql/sangria-akka-streams#2]
There doesn't seem to be a PR for 2.13 support for this library, unlike the rest of the Sangria libs.
I'm taking a look at adding this right now.
Looking at [the sangria-monix PR](https://github.com/sangria-graphql-org/sangria-monix/pull/1), there are also other changes like using `sbt-release` and adding MiMa. Should these also be made here? I don't have much experience with writing packages to be published to a public repository.
Some guidance from e.g. @travisbrown would be most welcome.

**Comment by travisbrown** [comment]
Thanks, @mjadczak!

A couple of things: you may have seen [our note](https://github.com/sangria-graphql/sangria/issues/446#issuecomment-546281588) from this morning, but if not, please open any PRs like this against [the `sangria-graphql-org` forks](https://github.com/sangria-graphql-org/sangria-akka-streams), since we don't have admin access to this organization for now.

I've been adding sbt-mima and sbt-release to all of the 2.13 PRs I've done so far because these make the release process a lot easier, but it's not really necessary—it'd be helpful for us to get a 2.13 PR for sangria-akka-streams even if it didn't include those parts. I'm happy to review either or both.

**Comment by travisbrown** [comment]
By the way there's a complete list of what's done and not done here—it might be a good idea to comment to avoid duplicated work: https://github.com/sangria-graphql/sangria/issues/440#issuecomment-546398600

**Comment by mjadczak** [comment]
Looks like this is resolved by sangria-graphql-org/sangria-akka-streams#10
